export type Language = keyof typeof TEXTS;

export const TEXTS = {
	en: {
		appTitle: 'How many units to...',
		appTagline: 'Professional Unit Converter',
		selectCategory: 'Unit Categories',
		categoryDescription: 'Choose a measurement category to begin converting',
		from: 'From',
		to: 'To',
		enterValue: 'Enter value',
		result: 'Result',
		conversionRate: 'Conversion Rate',
		swapUnits: 'Swap units',
		units: 'units',
		categories: {
			length: { name: 'Length', description: 'Convert between different length units' },
			weight: { name: 'Weight', description: 'Convert between different weight units' },
			volume: { name: 'Volume', description: 'Convert between different volume units' },
			temperature: {
				name: 'Temperature',
				description: 'Convert between different temperature units'
			},
			pressure: { name: 'Pressure', description: 'Convert between different pressure units' },
			area: { name: 'Area', description: 'Convert between different area units' },
			speed: { name: 'Speed', description: 'Convert between different speed units' },
			energy: { name: 'Energy', description: 'Convert between different energy units' }
		},
		unitNames: {
			// Length
			meter: 'Meter',
			kilometer: 'Kilometer',
			centimeter: 'Centimeter',
			millimeter: 'Millimeter',
			inch: 'Inch',
			foot: 'Foot',
			yard: 'Yard',
			mile: 'Mile',
			// Weight
			kilogram: 'Kilogram',
			gram: 'Gram',
			pound: 'Pound',
			ounce: 'Ounce',
			ton: 'Ton',
			stone: 'Stone',
			// Volume
			liter: 'Liter',
			milliliter: 'Milliliter',
			gallon: 'Gallon',
			quart: 'Quart',
			pint: 'Pint',
			cup: 'Cup',
			fluid_ounce: 'Fluid Ounce',
			cubic_meter: 'Cubic Meter',
			// Temperature
			celsius: 'Celsius',
			fahrenheit: 'Fahrenheit',
			kelvin: 'Kelvin',
			// Pressure
			pascal: 'Pascal',
			kilopascal: 'Kilopascal',
			bar: 'Bar',
			atmosphere: 'Atmosphere',
			psi: 'PSI',
			torr: 'Torr',
			// Area
			square_meter: 'Square Meter',
			square_kilometer: 'Square Kilometer',
			square_centimeter: 'Square Centimeter',
			square_inch: 'Square Inch',
			square_foot: 'Square Foot',
			acre: 'Acre',
			hectare: 'Hectare',
			// Speed
			meter_per_second: 'Meter per Second',
			kilometer_per_hour: 'Kilometer per Hour',
			mile_per_hour: 'Mile per Hour',
			foot_per_second: 'Foot per Second',
			knot: 'Knot',
			// Energy
			joule: 'Joule',
			kilojoule: 'Kilojoule',
			calorie: 'Calorie',
			kilocalorie: 'Kilocalorie',
			watt_hour: 'Watt Hour',
			kilowatt_hour: 'Kilowatt Hour',
			btu: 'BTU'
		},
		// Scale visualization
		dangerScale: 'Danger Scale',
		scaleComparison: 'Scale Comparison',
		extremeValues: 'Extreme Values',
		safe: 'Safe',
		caution: 'Caution',
		warning: 'Warning',
		danger: 'Danger',
		extreme: 'Extreme',
		// Temperature descriptions
		tempSafe: 'Safe temperature for humans',
		tempHot: 'Hot but tolerable for short periods',
		tempDangerous: 'Can cause burns and injury',
		tempLethal: 'Lethal temperature - immediate danger',
		tempExtreme: 'Extreme temperature - instant death',
		// Pressure descriptions
		pressureSafe: 'Normal atmospheric pressure',
		pressureUncomfortable: 'Uncomfortable but survivable',
		pressureDangerous: 'Can cause serious injury',
		pressureLethal: 'Lethal pressure levels',
		pressureExtreme: 'Extreme pressure - instant death',
		// Energy descriptions
		energyLow: 'Low energy levels',
		energyModerate: 'Moderate energy levels',
		energyHigh: 'High energy levels',
		energyDangerous: 'Dangerous energy levels',
		energyLethal: 'Lethal energy levels',
		// Larger beings
		elephantDescription: 'Could affect large mammals',
		whaleDescription: 'Could affect the largest animals',
		buildingDescription: 'Could damage structures',
		// Scale items translations
		scaleItems: {
			// Length
			virus: 'Virus',
			bacteria: 'Bacteria',
			hair: 'Hair',
			ant: 'Ant',
			coin: 'Coin',
			hand: 'Hand',
			person: 'Person',
			car: 'Car',
			house: 'House',
			building: 'Building',
			mountain: 'Mountain',
			earth: 'Earth',
			// Weight
			feather: 'Feather',
			phone: 'Phone',
			book: 'Book',
			cat: 'Cat',
			piano: 'Piano',
			elephant: 'Elephant',
			truck: 'Truck',
			whale: 'Whale',
			// Volume
			teaspoon: 'Teaspoon',
			shotGlass: 'Shot Glass',
			cup: 'Cup',
			bottle: 'Bottle',
			milkJug: 'Milk Jug',
			bucket: 'Bucket',
			bathtub: 'Bathtub',
			hotTub: 'Hot Tub',
			pool: 'Pool',
			// Area
			stamp: 'Stamp',
			sheet: 'Sheet',
			door: 'Door',
			room: 'Room',
			footballField: 'Football Field',
			cityBlock: 'City Block',
			centralPark: 'Central Park',
			// Speed
			walking: 'Walking',
			running: 'Running',
			cycling: 'Cycling',
			carCity: 'Car City',
			carHighway: 'Car Highway',
			cheetah: 'Cheetah',
			train: 'Train',
			airplane: 'Airplane',
			sound: 'Sound'
		}
	},
	es: {
		appTitle: 'Cuantas unidades para...',
		appTagline: 'Conversor Profesional de Unidades',
		selectCategory: 'Categorías de Unidades',
		categoryDescription: 'Elige una categoría de medición para comenzar a convertir',
		from: 'De',
		to: 'A',
		enterValue: 'Ingresa valor',
		result: 'Resultado',
		conversionRate: 'Tasa de Conversión',
		swapUnits: 'Intercambiar unidades',
		units: 'unidades',
		categories: {
			length: { name: 'Longitud', description: 'Convierte entre diferentes unidades de longitud' },
			weight: { name: 'Peso', description: 'Convierte entre diferentes unidades de peso' },
			volume: { name: 'Volumen', description: 'Convierte entre diferentes unidades de volumen' },
			temperature: {
				name: 'Temperatura',
				description: 'Convierte entre diferentes unidades de temperatura'
			},
			pressure: { name: 'Presión', description: 'Convierte entre diferentes unidades de presión' },
			area: { name: 'Área', description: 'Convierte entre diferentes unidades de área' },
			speed: { name: 'Velocidad', description: 'Convierte entre diferentes unidades de velocidad' },
			energy: { name: 'Energía', description: 'Convierte entre diferentes unidades de energía' }
		},
		unitNames: {
			// Length
			meter: 'Metro',
			kilometer: 'Kilómetro',
			centimeter: 'Centímetro',
			millimeter: 'Milímetro',
			inch: 'Pulgada',
			foot: 'Pie',
			yard: 'Yarda',
			mile: 'Milla',
			// Weight
			kilogram: 'Kilogramo',
			gram: 'Gramo',
			pound: 'Libra',
			ounce: 'Onza',
			ton: 'Tonelada',
			stone: 'Piedra',
			// Volume
			liter: 'Litro',
			milliliter: 'Mililitro',
			gallon: 'Galón',
			quart: 'Cuarto',
			pint: 'Pinta',
			cup: 'Taza',
			fluid_ounce: 'Onza Líquida',
			cubic_meter: 'Metro Cúbico',
			// Temperature
			celsius: 'Celsius',
			fahrenheit: 'Fahrenheit',
			kelvin: 'Kelvin',
			// Pressure
			pascal: 'Pascal',
			kilopascal: 'Kilopascal',
			bar: 'Bar',
			atmosphere: 'Atmósfera',
			psi: 'PSI',
			torr: 'Torr',
			// Area
			square_meter: 'Metro Cuadrado',
			square_kilometer: 'Kilómetro Cuadrado',
			square_centimeter: 'Centímetro Cuadrado',
			square_inch: 'Pulgada Cuadrada',
			square_foot: 'Pie Cuadrado',
			acre: 'Acre',
			hectare: 'Hectárea',
			// Speed
			meter_per_second: 'Metro por Segundo',
			kilometer_per_hour: 'Kilómetro por Hora',
			mile_per_hour: 'Milla por Hora',
			foot_per_second: 'Pie por Segundo',
			knot: 'Nudo',
			// Energy
			joule: 'Julio',
			kilojoule: 'Kilojulio',
			calorie: 'Caloría',
			kilocalorie: 'Kilocaloría',
			watt_hour: 'Vatio Hora',
			kilowatt_hour: 'Kilovatio Hora',
			btu: 'BTU'
		},
		// Scale visualization
		dangerScale: 'Escala de Peligro',
		scaleComparison: 'Comparación de Escalas',
		extremeValues: 'Valores Extremos',
		safe: 'Seguro',
		caution: 'Precaución',
		warning: 'Advertencia',
		danger: 'Peligro',
		extreme: 'Extremo',
		// Temperature descriptions
		tempSafe: 'Temperatura segura para humanos',
		tempHot: 'Caliente pero tolerable por períodos cortos',
		tempDangerous: 'Puede causar quemaduras y lesiones',
		tempLethal: 'Temperatura letal - peligro inmediato',
		tempExtreme: 'Temperatura extrema - muerte instantánea',
		// Pressure descriptions
		pressureSafe: 'Presión atmosférica normal',
		pressureUncomfortable: 'Incómoda pero sobrevivible',
		pressureDangerous: 'Puede causar lesiones graves',
		pressureLethal: 'Niveles de presión letales',
		pressureExtreme: 'Presión extrema - muerte instantánea',
		// Energy descriptions
		energyLow: 'Niveles de energía bajos',
		energyModerate: 'Niveles de energía moderados',
		energyHigh: 'Niveles de energía altos',
		energyDangerous: 'Niveles de energía peligrosos',
		energyLethal: 'Niveles de energía letales',
		// Larger beings
		elephantDescription: 'Podría afectar a mamíferos grandes',
		whaleDescription: 'Podría afectar a los animales más grandes',
		buildingDescription: 'Podría dañar estructuras',
		// Scale items translations
		scaleItems: {
			// Length
			virus: 'Virus',
			bacteria: 'Bacteria',
			hair: 'Cabello',
			ant: 'Hormiga',
			coin: 'Moneda',
			hand: 'Mano',
			person: 'Persona',
			car: 'Auto',
			house: 'Casa',
			building: 'Edificio',
			mountain: 'Montaña',
			earth: 'Tierra',
			// Weight
			feather: 'Pluma',
			phone: 'Teléfono',
			book: 'Libro',
			cat: 'Gato',
			piano: 'Piano',
			elephant: 'Elefante',
			truck: 'Camión',
			whale: 'Ballena',
			// Volume
			teaspoon: 'Cucharadita',
			shotGlass: 'Vaso de Shot',
			cup: 'Taza',
			bottle: 'Botella',
			milkJug: 'Jarra de Leche',
			bucket: 'Balde',
			bathtub: 'Bañera',
			hotTub: 'Jacuzzi',
			pool: 'Piscina',
			// Area
			stamp: 'Estampilla',
			sheet: 'Hoja',
			door: 'Puerta',
			room: 'Habitación',
			footballField: 'Campo de Fútbol',
			cityBlock: 'Manzana',
			centralPark: 'Parque Central',
			// Speed
			walking: 'Caminando',
			running: 'Corriendo',
			cycling: 'Ciclismo',
			carCity: 'Auto Ciudad',
			carHighway: 'Auto Autopista',
			cheetah: 'Guepardo',
			train: 'Tren',
			airplane: 'Avión',
			sound: 'Sonido'
		}
	}
};